### ISSUE TITLE
Crash with bank storage

### ISSUE THREAD

**Issue by Natanaelel** [CloudG360/Survival-Building-Toolkit#34]
https://github.com/Natanaelel/BankStorage/issues/45
https://github.com/squeeglii/BridgingMod/issues/29
SavedData cannot be accessed from the client.
`CachedBankStorage` is the class to use on the client. It gets synced automatically.
Feel free to ask questions about implementation.

**Comment by squeeglii** [comment]
Fixed! I should've tested it with a server - My bad.
Bug fix will be out soon.

**Comment by Gbergz** [comment]
Hey, any clue on when it's being released?

**Comment by squeeglii** [comment]
Should be out saturday at the latest

**Comment by JWTHDYTWA** [comment]
> Should be out saturday at the latest

It's still an issue in 2.6.1. Again, `Bank Storage` and `Bridging Mod`. [[Crashlog]](https://gist.github.com/JWTHDYTWA/11a458c8c7805c2bf4aa9560d1f60efc)
